# Generated by Django 4.1.7 on 2023-03-12 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=50, null=True, verbose_name='Antecedente patológico personal')),
            ],
            options={
                'verbose_name': 'Antecedente patológico personal',
                'verbose_name_plural': 'Antecedentes patológicos personales',
                'db_table': 'app',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=50, null=True, verbose_name='Diagnóstico')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'db_table': 'diagnostico',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'db_table': 'sala',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('direccion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección')),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to='pefil/', verbose_name='Imagen de perfil')),
                ('cama', models.CharField(max_length=255, null=True, verbose_name='Cama')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.app', verbose_name='APP')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.diagnostico', verbose_name='Diagnóstico')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.raza', verbose_name='Raza')),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.sala', verbose_name='Sala')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.sexo', verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
            },
        ),
    ]
